version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: umrah
      POSTGRES_PASSWORD: umrah
      POSTGRES_DB: umrah
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  gateway:
    build: ./services/gateway
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: http://auth:8081
      CATALOG_SERVICE_URL: http://catalog:8082
      BOOKING_SERVICE_URL: http://booking:8083
      PAYMENT_SERVICE_URL: http://payment:8084
      CORS_ALLOWED_ORIGINS: http://localhost:5173
      JWT_SECRET: ${JWT_SECRET:-change-me-please-change-me-please-123456}
    depends_on:
      - auth
      - catalog
      - booking
      - payment

  auth:
    build: ./services/auth
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: umrah
      DB_USER: umrah
      DB_PASSWORD: umrah
      JWT_SECRET: ${JWT_SECRET:-change-me-please-change-me-please-123456}
      GOOGLE_CLIENT_ID: 619516920511-73vcvhuff2f97k70vf3g3fcta2f4a32b.apps.googleusercontent.com
    depends_on:
      - postgres

  catalog:
    build: ./services/catalog
    ports:
      - "8082:8082"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: umrah
      DB_USER: umrah
      DB_PASSWORD: umrah
    depends_on:
      - postgres

  booking:
    build: ./services/booking
    ports:
      - "8083:8083"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: umrah
      DB_USER: umrah
      DB_PASSWORD: umrah
    depends_on:
      - postgres

  payment:
    build: ./services/payment
    ports:
      - "8084:8084"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: umrah
      DB_USER: umrah
      DB_PASSWORD: umrah
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_PROXY_TARGET: http://gateway:8080
      VITE_GOOGLE_CLIENT_ID: 619516920511-73vcvhuff2f97k70vf3g3fcta2f4a32b.apps.googleusercontent.com
    depends_on:
      - gateway
