server:
  port: 8081

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:umrah}?currentSchema=auth
    username: ${DB_USER:umrah}
    password: ${DB_PASSWORD:umrah}
  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: ${JWT_SECRET:change-me-please-change-me-please-123456}
    issuer: almuhammad
    expiresMinutes: 120
  google:
    clientId: ${GOOGLE_CLIENT_ID:619516920511-4k3a6g5973a04p57d76rhhp6h23eutkj.apps.googleusercontent.com}
  otp:
    expiresMinutes: ${OTP_EXPIRES_MINUTES:5}
    exposeInResponse: ${OTP_EXPOSE_IN_RESPONSE:true}
