server:
  port: 8084

spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:umrah}?currentSchema=payment
    username: ${DB_USER:umrah}
    password: ${DB_PASSWORD:umrah}
  jpa:
    hibernate:
      ddl-auto: update

razorpay:
  key-id: ${RAZORPAY_KEY_ID:}
  key-secret: ${RAZORPAY_KEY_SECRET:}
